library(shiny)
library(DRomics)
library(ggplot2)
library(shinyjs)
library(shinyBS)
library(shinycssloaders)
addResourcePath('DRomicspkg', system.file("extdata", package="DRomics"))
options(shiny.maxRequestSize=30*1024^2)